[package]
name = "lax"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

[features]
default = []

netlib    = ["netlib-static"]
openblas  = ["openblas-static"]
intel-mkl = ["intel-mkl-static"]

netlib-static = ["netlib-src/static"]
netlib-system = ["netlib-src/system"]

openblas-static = ["openblas-src/static"]
openblas-system = ["openblas-src/system"]

intel-mkl-static = ["intel-mkl-src/mkl-static-lp64-seq", "intel-mkl-src/download"]
intel-mkl-system = ["intel-mkl-src/mkl-dynamic-lp64-seq"]

[dependencies]
thiserror = "1.0"
cauchy = "0.2.0"
num-traits = "0.2"
lapack = "0.16.0"

[dependencies.intel-mkl-src]
version = "0.6.0"
default-features = false
optional = true

[dependencies.netlib-src]
version = "0.8.0"
optional = true
features = ["cblas"]
default-features = false

[dependencies.openblas-src]
git = "https://github.com/blas-lapack-rs/openblas-src.git"
tag = "0.10.1"
optional = true
default-features = false
features = ["cblas"]
